spring:
  application:
    name: auth-service
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: yixupi
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
